version: '2'
services:
  control:
    container_name: jepsen-control-zookeeper
    hostname: control
    build: ./control
    env_file: ./secret/control.env
    privileged: true
    links:
      - n1
      - n2
      - n3
      - n4
      - n5
  node:
    container_name: jepsen-node-zookeeper
    build: ./node
    env_file: ./secret/node.env
    privileged: true
  n1:
    extends: node
    container_name: jepsen-n1-zookeeper
    hostname: n1
  n2:
    extends: node
    container_name: jepsen-n2-zookeeper
    hostname: n2
  n3:
    extends: node
    container_name: jepsen-n3-zookeeper
    hostname: n3
  n4:
    extends: node
    container_name: jepsen-n4-zookeeper
    hostname: n4
  n5:
    extends: node
    container_name: jepsen-n5-zookeeper
    hostname: n5
